name: CoreMMO
version: '1.0-SNAPSHOT'
main: br.com.ruasvivas.coreMMO.CoreMMO
api-version: '1.21'
commands:
  curar:
    description: Recupera vida e fome do jogador.
    usage: /curar
  espada:
    description: Dá uma espada lendária ao jogador.
    usage: /espada
  classe:
    description: Abre o menu de seleção de classes.
    usage: /classe
  saldo:
    description: Mostra quanto dinheiro você tem.
    usage: /saldo
  pagar:
    description: Envia dinheiro para outro jogador.
    usage: /pagar <jogador> <valor>