name: CoreMMO
version: ${project.version}
main: br.com.ruasvivas.gameplay.CorePlugin
api-version: 1.21 # Ou a versão que você está usando (1.20, 1.21)
authors: [ gothd ]
depend: [ ] # Se tiver dependências soft como Vault, coloque aqui

commands:
  classe:
    description: Abre o menu de escolha de classes.
    usage: /classe
    aliases: [ job, profissao ]

  pagar:
    description: Envia dinheiro para outro jogador.
    usage: /pagar <jogador> <valor>
    aliases: [ pay ]

  saldo:
    description: Mostra quanto dinheiro você tem.
    usage: /saldo
    aliases: [ money, bal, balance ]

  guilda:
    description: Sistema de guildas e clãs.
    usage: /guilda <subcomando>
    aliases: [ clan, g ]

  stats:
    description: Exibe detalhes dos atributos.
    usage: /stats
    aliases: [ mmo ]

  # Comandos Administrativos (A verificação é feita no Java para customizar a mensagem)
  reloadmmo:
    description: Recarrega as configurações.
    usage: /reloadmmo

  grant:
    description: Adiciona permissão a um jogador.
    usage: /grant <jogador> <permissao>

  revoke:
    description: Remove permissão de um jogador.
    usage: /revoke <jogador> <permissao>

  kick:
    description: Expulsa um jogador do servidor.
    usage: /kick <jogador> [motivo]

  giverpg:
    description: Gera um item RPG aleatório baseado em nível.
    usage: /giverpg <jogador> <nivel>
    permission: coremmo.admin

  npc:
    description: Gerencia posicionamento de NPCs.
    usage: /npc set <id>

# Registro das Permissões
permissions:
  coremmo.mod:
    description: Permissão básica para moderadores (Kick).
    default: op

  coremmo.admin:
    description: Permissão total de administração.
    default: op
    children:
      coremmo.mod: true